apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  namespace: default  #EKS에서 사용할 네임스페이스
spec:
  replicas: 2  #2개의 Pod 사용
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api-container
          image: 827146411697.dkr.ecr.us-east-1.amazonaws.com/rest-api:latest  #ECR 이미지 사용
          imagePullPolicy: IfNotPresent  #캐시 활용 가능
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE  #환경 변수 추가 (예: prod, dev)
              value: "prod"
          resources:   #리소스 요청 및 제한 추가
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
